### ISSUE TITLE
Preview 進入後介紹專案分工方式 - 紫薯

### ISSUE THREAD

**Issue by Ateto1204** [we-we-Web/web-web-web#22]
## 後端
- 蘇東毅：全部

## 前端
- 王鈞宇：抽籤動畫
- 林彥均：匯出 Excel 抽籤結果
- JC：登入畫面
- 蘇東毅：資料綁定、畫面跳轉、UI/UX 優化

**Comment by cjc094** [comment]
![Image](https://github.com/user-attachments/assets/c9e3c7cf-fae1-4787-a663-88d06f35e4f7)
